package com.zhqz.faces.data.DbDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhqz.faces.data.model.FacesData;

import com.zhqz.faces.data.DbDao.FacesDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig facesDataDaoConfig;

    private final FacesDataDao facesDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        facesDataDaoConfig = daoConfigMap.get(FacesDataDao.class).clone();
        facesDataDaoConfig.initIdentityScope(type);

        facesDataDao = new FacesDataDao(facesDataDaoConfig, this);

        registerDao(FacesData.class, facesDataDao);
    }
    
    public void clear() {
        facesDataDaoConfig.clearIdentityScope();
    }

    public FacesDataDao getFacesDataDao() {
        return facesDataDao;
    }

}
