package com.zhqz.faces.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhqz.faces.data.model.FacesData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACES_DATA".
*/
public class FacesDataDao extends AbstractDao<FacesData, Void> {

    public static final String TABLENAME = "FACES_DATA";

    /**
     * Properties of entity FacesData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property Sex = new Property(1, String.class, "sex", false, "SEX");
        public final static Property MImagePath = new Property(2, String.class, "mImagePath", false, "M_IMAGE_PATH");
        public final static Property MFaceRect = new Property(3, String.class, "mFaceRect", false, "M_FACE_RECT");
        public final static Property MFeature = new Property(4, String.class, "mFeature", false, "M_FEATURE");
    }


    public FacesDataDao(DaoConfig config) {
        super(config);
    }
    
    public FacesDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACES_DATA\" (" + //
                "\"NAME\" TEXT," + // 0: name
                "\"SEX\" TEXT," + // 1: sex
                "\"M_IMAGE_PATH\" TEXT," + // 2: mImagePath
                "\"M_FACE_RECT\" TEXT," + // 3: mFaceRect
                "\"M_FEATURE\" TEXT);"); // 4: mFeature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACES_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FacesData entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(2, sex);
        }
 
        String mImagePath = entity.getMImagePath();
        if (mImagePath != null) {
            stmt.bindString(3, mImagePath);
        }
 
        String mFaceRect = entity.getMFaceRect();
        if (mFaceRect != null) {
            stmt.bindString(4, mFaceRect);
        }
 
        String mFeature = entity.getMFeature();
        if (mFeature != null) {
            stmt.bindString(5, mFeature);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FacesData entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(2, sex);
        }
 
        String mImagePath = entity.getMImagePath();
        if (mImagePath != null) {
            stmt.bindString(3, mImagePath);
        }
 
        String mFaceRect = entity.getMFaceRect();
        if (mFaceRect != null) {
            stmt.bindString(4, mFaceRect);
        }
 
        String mFeature = entity.getMFeature();
        if (mFeature != null) {
            stmt.bindString(5, mFeature);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public FacesData readEntity(Cursor cursor, int offset) {
        FacesData entity = new FacesData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // sex
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mImagePath
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mFaceRect
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // mFeature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FacesData entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSex(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMImagePath(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMFaceRect(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMFeature(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(FacesData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(FacesData entity) {
        return null;
    }

    @Override
    public boolean hasKey(FacesData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
