package com.zhqz.faces.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhqz.faces.data.model.FacesData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACES_DATA".
*/
public class FacesDataDao extends AbstractDao<FacesData, Void> {

    public static final String TABLENAME = "FACES_DATA";

    /**
     * Properties of entity FacesData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property MImagePath = new Property(0, String.class, "mImagePath", false, "M_IMAGE_PATH");
        public final static Property MThumbnailPath = new Property(1, String.class, "mThumbnailPath", false, "M_THUMBNAIL_PATH");
        public final static Property MFeatureIndex = new Property(2, int.class, "mFeatureIndex", false, "M_FEATURE_INDEX");
        public final static Property MByteFeature = new Property(3, byte[].class, "mByteFeature", false, "M_BYTE_FEATURE");
        public final static Property MFaceRect = new Property(4, String.class, "mFaceRect", false, "M_FACE_RECT");
        public final static Property MFeature = new Property(5, String.class, "mFeature", false, "M_FEATURE");
    }


    public FacesDataDao(DaoConfig config) {
        super(config);
    }
    
    public FacesDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACES_DATA\" (" + //
                "\"M_IMAGE_PATH\" TEXT," + // 0: mImagePath
                "\"M_THUMBNAIL_PATH\" TEXT," + // 1: mThumbnailPath
                "\"M_FEATURE_INDEX\" INTEGER NOT NULL ," + // 2: mFeatureIndex
                "\"M_BYTE_FEATURE\" BLOB," + // 3: mByteFeature
                "\"M_FACE_RECT\" TEXT," + // 4: mFaceRect
                "\"M_FEATURE\" TEXT);"); // 5: mFeature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACES_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FacesData entity) {
        stmt.clearBindings();
 
        String mImagePath = entity.getMImagePath();
        if (mImagePath != null) {
            stmt.bindString(1, mImagePath);
        }
 
        String mThumbnailPath = entity.getMThumbnailPath();
        if (mThumbnailPath != null) {
            stmt.bindString(2, mThumbnailPath);
        }
        stmt.bindLong(3, entity.getMFeatureIndex());
 
        byte[] mByteFeature = entity.getMByteFeature();
        if (mByteFeature != null) {
            stmt.bindBlob(4, mByteFeature);
        }
 
        String mFaceRect = entity.getMFaceRect();
        if (mFaceRect != null) {
            stmt.bindString(5, mFaceRect);
        }
 
        String mFeature = entity.getMFeature();
        if (mFeature != null) {
            stmt.bindString(6, mFeature);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FacesData entity) {
        stmt.clearBindings();
 
        String mImagePath = entity.getMImagePath();
        if (mImagePath != null) {
            stmt.bindString(1, mImagePath);
        }
 
        String mThumbnailPath = entity.getMThumbnailPath();
        if (mThumbnailPath != null) {
            stmt.bindString(2, mThumbnailPath);
        }
        stmt.bindLong(3, entity.getMFeatureIndex());
 
        byte[] mByteFeature = entity.getMByteFeature();
        if (mByteFeature != null) {
            stmt.bindBlob(4, mByteFeature);
        }
 
        String mFaceRect = entity.getMFaceRect();
        if (mFaceRect != null) {
            stmt.bindString(5, mFaceRect);
        }
 
        String mFeature = entity.getMFeature();
        if (mFeature != null) {
            stmt.bindString(6, mFeature);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public FacesData readEntity(Cursor cursor, int offset) {
        FacesData entity = new FacesData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // mImagePath
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mThumbnailPath
            cursor.getInt(offset + 2), // mFeatureIndex
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // mByteFeature
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mFaceRect
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // mFeature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FacesData entity, int offset) {
        entity.setMImagePath(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setMThumbnailPath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMFeatureIndex(cursor.getInt(offset + 2));
        entity.setMByteFeature(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setMFaceRect(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMFeature(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(FacesData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(FacesData entity) {
        return null;
    }

    @Override
    public boolean hasKey(FacesData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
