package com.zhqz.faces.data.DbDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhqz.faces.data.model.FacesData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FACES_DATA".
*/
public class FacesDataDao extends AbstractDao<FacesData, Long> {

    public static final String TABLENAME = "FACES_DATA";

    /**
     * Properties of entity FacesData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Sex = new Property(2, String.class, "sex", false, "SEX");
        public final static Property MImagePath = new Property(3, String.class, "mImagePath", false, "M_IMAGE_PATH");
        public final static Property MFaceRect = new Property(4, String.class, "mFaceRect", false, "M_FACE_RECT");
        public final static Property MFeature = new Property(5, String.class, "mFeature", false, "M_FEATURE");
    }


    public FacesDataDao(DaoConfig config) {
        super(config);
    }
    
    public FacesDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FACES_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"SEX\" TEXT," + // 2: sex
                "\"M_IMAGE_PATH\" TEXT," + // 3: mImagePath
                "\"M_FACE_RECT\" TEXT," + // 4: mFaceRect
                "\"M_FEATURE\" TEXT);"); // 5: mFeature
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FACES_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FacesData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(3, sex);
        }
 
        String mImagePath = entity.getMImagePath();
        if (mImagePath != null) {
            stmt.bindString(4, mImagePath);
        }
 
        String mFaceRect = entity.getMFaceRect();
        if (mFaceRect != null) {
            stmt.bindString(5, mFaceRect);
        }
 
        String mFeature = entity.getMFeature();
        if (mFeature != null) {
            stmt.bindString(6, mFeature);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FacesData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String sex = entity.getSex();
        if (sex != null) {
            stmt.bindString(3, sex);
        }
 
        String mImagePath = entity.getMImagePath();
        if (mImagePath != null) {
            stmt.bindString(4, mImagePath);
        }
 
        String mFaceRect = entity.getMFaceRect();
        if (mFaceRect != null) {
            stmt.bindString(5, mFaceRect);
        }
 
        String mFeature = entity.getMFeature();
        if (mFeature != null) {
            stmt.bindString(6, mFeature);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public FacesData readEntity(Cursor cursor, int offset) {
        FacesData entity = new FacesData( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // sex
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // mImagePath
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mFaceRect
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // mFeature
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FacesData entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSex(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMImagePath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMFaceRect(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setMFeature(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FacesData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FacesData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FacesData entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
